version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.11-management
    restart:
      always
    environment:
      RABBITMQ_DEFAULT_USER: rmuser
      RABBITMQ_DEFAULT_PASS: rmpassword
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  notification_api:
    build: notification_service
    container_name: notification_api
    ports:
      - "8080:8080"
    depends_on:
     - rabbitmq
     - notifications_db
    restart:
      always
    env_file:
    - envs/.env
    volumes:
      - ./notification_service:/notification_service

  notifications_db:
    image: postgres:14.3
    container_name: notifications_db
    env_file:
      - envs/.env
    volumes:
      - db:/var/lib/postgresql/data
      - ./admin/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  admin:
    build: admin
    env_file:
      - envs/.env
    depends_on:
      - notifications_db
    volumes:
      - static:/admin/static/
      - media:/admin/media/
      - ./admin:/admin
    ports:
      - "8000:8000"

volumes:
  static:
  media:
  db: