version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.11-management
    restart:
      always
    environment:
      RABBITMQ_DEFAULT_USER: rmuser
      RABBITMQ_DEFAULT_PASS: rmpassword
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  notification_api:
    build: notification_service
    container_name: notification_api
    ports:
      - "8080:8080"
    depends_on:
     - rabbitmq
     - notifications_db
    restart:
      always
    env_file:
    - envs/.env
    volumes:
      - ./notification_service:/notification_service

  notifications_db:
    image: postgres:14.3
    container_name: notifications_db
    env_file:
      - envs/.env
    volumes:
      - db:/var/lib/postgresql/data
      - ./admin/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  admin:
    build: admin
    env_file:
      - envs/.env
    depends_on:
      - notifications_db
    volumes:
      - static:/admin/static/
      - media:/admin/media/
      - ./admin:/admin
    ports:
      - "8000:8000"

  worker:
    build: worker
    image: worker
    volumes:
      - .worker/:/app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    image: worker
    command: celery -A tasks worker --loglevel=INFO
    volumes:
      - .worker/:/app

  #Clickhouse
  zookeeper:
    image: zookeeper:3.5
    container_name: zookeeper
    hostname: zookeeper

  clickhouse-node1:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./worker/clickhouse/node1:/etc/clickhouse-server
    depends_on:
      - zookeeper

  clickhouse-node2:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    volumes:
      - ./worker/clickhouse/node2:/etc/clickhouse-server
    depends_on:
      - zookeeper

  clickhouse-node3:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    volumes:
      - ./worker/clickhouse/node3:/etc/clickhouse-server
    depends_on:
      - zookeeper

  clickhouse-node4:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-node4
    hostname: clickhouse-node4
    volumes:
      - ./worker/clickhouse/node4:/etc/clickhouse-server
    depends_on:
      - zookeeper

volumes:
  static:
  media:
  db: